import type { CharacterPreset, Skill, CharacterType } from '../types';

// ============================================
// 🎭 CHARACTER PRESETS (Honkai Sci-Fi Style)
// ============================================
export const CHARACTER_PRESETS: Record<string, CharacterPreset> = {
  rudeus: {
    type: 'rudeus',
    name: 'Rudeus Greyrat',
    baseHealth: 100,
    baseMana: 150,
    baseAttack: 25,
    baseDefense: 15,
    baseSpeed: 10,
    skills: ['fireball', 'ice-shield', 'heal', 'teleport'],
    model: 'rudeus',
    color: 0x4a90d9,
    description: 'The reincarnated prodigy mage with vast magical knowledge',
    outfit: 'blue_robe',
    hairColor: 0x4a90d9,
    hairStyle: 'medium',
    age: 'teen',
  },
  warrior: {
    type: 'warrior',
    name: 'Cyber Knight',
    baseHealth: 120,
    baseMana: 60,
    baseAttack: 25,
    baseDefense: 25,
    baseSpeed: 8,
    skills: ['plasma-slash', 'energy-shield', 'ion-cannon', 'overcharge'],
    model: 'warrior',
    color: 0x222233,
    description: 'A cybernetically enhanced warrior with energy weapons',
    outfit: 'cyber_armor',
    hairColor: 0x444455,
    hairStyle: 'short',
    age: 'adult',
  },
  mage: {
    type: 'mage',
    name: 'Quantum Mage',
    baseHealth: 80,
    baseMana: 150,
    baseAttack: 30,
    baseDefense: 10,
    baseSpeed: 7,
    skills: ['quantum-blast', 'void-shield', 'gravity-well', 'phase-shift'],
    model: 'mage',
    color: 0x0066ff,
    description: 'A master of quantum energies and spatial manipulation',
    outfit: 'quantum_robe',
    hairColor: 0xffffff,
    hairStyle: 'long',
    age: 'adult',
  },
  rogue: {
    type: 'rogue',
    name: 'Phantom Agent',
    baseHealth: 90,
    baseMana: 80,
    baseAttack: 25,
    baseDefense: 15,
    baseSpeed: 14,
    skills: ['hologram-cloak', 'neural-disruptor', 'phase-dagger', 'quantum-blink'],
    model: 'rogue',
    color: 0x003322,
    description: 'A stealth operative with quantum cloaking technology',
    outfit: 'stealth_suit',
    hairColor: 0x228b22,
    hairStyle: 'short',
    age: 'adult',
  },
  archer: {
    type: 'archer',
    name: 'Stellar Sniper',
    baseHealth: 95,
    baseMana: 70,
    baseAttack: 25,
    baseDefense: 10,
    baseSpeed: 10,
    skills: ['photon-arrow', 'black-hole-trap', 'precision-strike', 'orbital-barrage'],
    model: 'archer',
    color: 0x330066,
    description: 'A long-range specialist with energy-based weaponry',
    outfit: 'tactical_gear',
    hairColor: 0xdaa520,
    hairStyle: 'ponytail',
    age: 'adult',
  },
  healer: {
    type: 'healer',
    name: 'Bio-Synth',
    baseHealth: 100,
    baseMana: 180,
    baseAttack: 10,
    baseDefense: 12,
    baseSpeed: 9,
    skills: ['nano-regeneration', 'stasis-field', 'neural-boost', 'bio-purge'],
    model: 'healer',
    color: 0x00ffff,
    description: 'A bio-engineered support specialist with healing nanites',
    outfit: 'medical_armor',
    hairColor: 0xffd700,
    hairStyle: 'long',
    age: 'adult',
  },
  abie: {
    type: 'abie',
    name: 'Draco Abielle',
    baseHealth: 98,
    baseMana: 165,
    baseAttack: 32,
    baseDefense: 18,
    baseSpeed: 14,
    skills: [
      'gale-arrow', 'thunder-fang', 'sky-piercer', 'tempest-volley',
      'cyclone-shot', 'storm-rain', 'gale-dance', 'lightning-cross',
      'phantom-step', 'storm-waltz', 'tempest-dominion',
      'heavens-thunder', 'horizon-breaker'
    ],
    model: 'abie',
    color: 0x008080,
    description: 'Marksman with mastery over wind, lightning, and water mana. Twin sister of Draco Noir.',
    outfit: 'marksman_gear',
    hairColor: 0x8B4513,
    hairStyle: 'short',
    age: 'young_adult',
    class: 'Marksman',
    race: 'Human',
    manaAffinities: ['Wind', 'Lightning', 'Water'],
    primaryWeapon: 'Stormcaller',
    secondaryWeapons: ['Zephyr', 'Tempest'],
  },
};

// ============================================
// ⚔️ SKILLS DATABASE (Honkai Sci-Fi Style)
// ============================================
export const SKILLS: Record<string, Skill> = {
  'fireball': { id: 'fireball', name: 'Plasma Fireball', description: 'Launches a ball of ionized plasma', type: 'attack', damage: 45, manaCost: 25, cooldown: 3000, range: 18 },
  'ice-shield': { id: 'ice-shield', name: 'Cryo Barrier', description: 'Creates a protective cryogenic shield', type: 'defense', manaCost: 20, cooldown: 8000, range: 1 },
  'heal': { id: 'heal', name: 'Nano Heal', description: 'Deploys healing nanobots to a target', type: 'heal', healAmount: 45, manaCost: 25, cooldown: 3000, range: 12 },
  'teleport': { id: 'teleport', name: 'Quantum Shift', description: 'Instantly teleport to a nearby location', type: 'utility', manaCost: 30, cooldown: 15000, range: 25 },
  'plasma-slash': { id: 'plasma-slash', name: 'Plasma Slash', description: 'A powerful energy-infused melee strike', type: 'attack', damage: 30, manaCost: 15, cooldown: 2000, range: 2.5 },
  'energy-shield': { id: 'energy-shield', name: 'Energy Shield', description: 'Creates a protective energy barrier', type: 'defense', manaCost: 20, cooldown: 6000, range: 1 },
  'ion-cannon': { id: 'ion-cannon', name: 'Ion Cannon', description: 'Fires a devastating ion beam', type: 'attack', damage: 50, manaCost: 35, cooldown: 8000, range: 20 },
  'overcharge': { id: 'overcharge', name: 'Overcharge', description: 'Boosts attack power temporarily', type: 'utility', manaCost: 25, cooldown: 12000, range: 1 },
  'quantum-blast': { id: 'quantum-blast', name: 'Quantum Blast', description: 'Releases unstable quantum energy', type: 'attack', damage: 55, manaCost: 30, cooldown: 4000, range: 22 },
  'void-shield': { id: 'void-shield', name: 'Void Shield', description: 'Creates a shield that absorbs energy attacks', type: 'defense', manaCost: 25, cooldown: 7000, range: 1 },
  'gravity-well': { id: 'gravity-well', name: 'Gravity Well', description: 'Creates a gravity field that pulls enemies in', type: 'utility', manaCost: 40, cooldown: 10000, range: 15 },
  'phase-shift': { id: 'phase-shift', name: 'Phase Shift', description: 'Become intangible for a short period', type: 'utility', manaCost: 35, cooldown: 18000, range: 1 },
  'hologram-cloak': { id: 'hologram-cloak', name: 'Hologram Cloak', description: 'Creates a holographic decoy', type: 'utility', manaCost: 20, cooldown: 10000, range: 1 },
  'neural-disruptor': { id: 'neural-disruptor', name: 'Neural Disruptor', description: 'Disables enemy targeting systems', type: 'attack', damage: 25, manaCost: 20, cooldown: 6000, range: 10 },
  'phase-dagger': { id: 'phase-dagger', name: 'Phase Dagger', description: 'A dagger that phases through defenses', type: 'attack', damage: 40, manaCost: 15, cooldown: 3000, range: 2 },
  'quantum-blink': { id: 'quantum-blink', name: 'Quantum Blink', description: 'Short-range teleportation', type: 'utility', manaCost: 25, cooldown: 8000, range: 10 },
  'photon-arrow': { id: 'photon-arrow', name: 'Photon Arrow', description: 'Fires a high-energy photon arrow', type: 'attack', damage: 35, manaCost: 20, cooldown: 2500, range: 30 },
  'black-hole-trap': { id: 'black-hole-trap', name: 'Black Hole Trap', description: 'Creates a gravity trap', type: 'utility', manaCost: 30, cooldown: 12000, range: 8 },
  'precision-strike': { id: 'precision-strike', name: 'Precision Strike', description: 'A perfectly aimed critical shot', type: 'attack', damage: 70, manaCost: 40, cooldown: 10000, range: 35 },
  'orbital-barrage': { id: 'orbital-barrage', name: 'Orbital Barrage', description: 'Calls down an orbital strike', type: 'attack', damage: 45, manaCost: 35, cooldown: 15000, range: 25 },
  'nano-regeneration': { id: 'nano-regeneration', name: 'Nano Regeneration', description: 'Heals over time with nanobots', type: 'heal', healAmount: 60, manaCost: 30, cooldown: 5000, range: 15 },
  'stasis-field': { id: 'stasis-field', name: 'Stasis Field', description: 'Puts allies in protective stasis', type: 'defense', manaCost: 35, cooldown: 15000, range: 12 },
  'neural-boost': { id: 'neural-boost', name: 'Neural Boost', description: 'Enhances ally reflexes and speed', type: 'utility', manaCost: 25, cooldown: 10000, range: 15 },
  'bio-purge': { id: 'bio-purge', name: 'Bio Purge', description: 'Removes toxins and debuffs', type: 'utility', manaCost: 20, cooldown: 8000, range: 12 },
  'gale-arrow': { id: 'gale-arrow', name: 'Gale Arrow', description: 'Fires an arrow infused with wind mana, pushing enemies back', type: 'attack', damage: 35, manaCost: 20, cooldown: 2500, range: 25, element: 'Wind', effect: 'knockback' },
  'sky-piercer': { id: 'sky-piercer', name: 'Sky Piercer', description: 'Launches a high-velocity arrow that pierces through multiple enemies', type: 'attack', damage: 45, manaCost: 30, cooldown: 5000, range: 30, element: 'Wind', effect: 'piercing' },
  'cyclone-shot': { id: 'cyclone-shot', name: 'Cyclone Shot', description: 'Creates a swirling wind vortex that damages enemies in area', type: 'attack', damage: 40, manaCost: 25, cooldown: 4000, range: 15, element: 'Wind', effect: 'aoe' },
  'storm-rain': { id: 'storm-rain', name: 'Storm Rain', description: 'Fires a volley of wind-infused arrows that rain down on targets', type: 'attack', damage: 30, manaCost: 35, cooldown: 6000, range: 20, element: 'Wind', effect: 'multi-hit' },
  'thunder-fang': { id: 'thunder-fang', name: 'Thunder Fang', description: 'Strikes with lightning-infused blades, electrifying the target', type: 'attack', damage: 38, manaCost: 22, cooldown: 3000, range: 2.5, element: 'Lightning', effect: 'stun' },
  'lightning-cross': { id: 'lightning-cross', name: 'Lightning Cross', description: 'Performs a cross-shaped slash with dual blades, releasing lightning energy', type: 'attack', damage: 50, manaCost: 35, cooldown: 5500, range: 3, element: 'Lightning', effect: 'aoe' },
  'heavens-thunder': { id: 'heavens-thunder', name: 'Heaven's Thunder', description: 'Calls down a massive lightning strike from the heavens', type: 'attack', damage: 75, manaCost: 50, cooldown: 12000, range: 20, element: 'Lightning', effect: 'stun' },
  'tempest-volley': { id: 'tempest-volley', name: 'Tempest Volley', description: 'Fires a rapid volley of arrows infused with wind and lightning', type: 'attack', damage: 28, manaCost: 30, cooldown: 4500, range: 25, element: 'Wind/Lightning', effect: 'multi-hit' },
  'tempest-dominion': { id: 'tempest-dominion', name: 'Tempest Dominion', description: 'Unleashes a storm of wind and lightning, damaging all enemies in a large area', type: 'attack', damage: 60, manaCost: 60, cooldown: 15000, range: 25, element: 'Wind/Lightning', effect: 'aoe' },
  'phantom-step': { id: 'phantom-step', name: 'Phantom Step', description: 'Quickly dashes a short distance, leaving an afterimage', type: 'utility', manaCost: 15, cooldown: 4000, range: 8, effect: 'dash' },
  'gale-dance': { id: 'gale-dance', name: 'Gale Dance', description: 'Performs a spinning attack with dual blades, creating a wind vortex', type: 'attack', damage: 35, manaCost: 25, cooldown: 4000, range: 3, element: 'Wind', effect: 'aoe' },
  'storm-waltz': { id: 'storm-waltz', name: 'Storm Waltz', description: 'A graceful combo attack alternating between bow and blades', type: 'attack', damage: 42, manaCost: 30, cooldown: 5000, range: 5, effect: 'combo' },
  'horizon-breaker': { id: 'horizon-breaker', name: 'Horizon Breaker', description: 'Fires a powerful arrow that creates a shockwave across the battlefield', type: 'attack', damage: 80, manaCost: 70, cooldown: 20000, range: 40, element: 'Wind/Lightning/Water', effect: 'line' },
};

// ============================================
// 🗺️ WORLD CONSTANTS
// ============================================
export const GAME_CONSTANTS = {
  WORLD_SIZE: 1000,
  GRAVITY: -9.8,
  PLAYER_SPEED: 0.25,
  PLAYER_HEIGHT: 1.8,
  PLAYER_RADIUS: 0.5,
  CAMERA_OFFSET: { x: 0, y: 2.5, z: -5 },
  MAX_PLAYERS: 50,
  TICK_RATE: 30,
  DEFAULT_HEALTH: 100,
  DEFAULT_MANA: 100,
};

// ============================================
// 🎨 WORLD SETTINGS (Honkai Sci-Fi Style)
// ============================================
export const WORLD_SETTINGS = {
  groundColor: 0x0a0a1a,
  skyColor: 0x000033,
  fogColor: 0x000022,
  fogDensity: 0.001,
  ambientLight: 0x1a1a33,
  directionalLight: 0x404066,
  animeShading: false,
  toonShading: true,
  bloomIntensity: 1.5,
  bloomThreshold: 0,
  bloomRadius: 0.4,
  toneMappingExposure: 1.2,
};

// Toon shading gradient texture for cel-shading
export const TOON_GRADIENT = {
  stops: [
    { position: 0.0, color: 0x000000 },
    { position: 0.25, color: 0x222244 },
    { position: 0.45, color: 0x444488 },
    { position: 0.65, color: 0x8888cc },
    { position: 0.85, color: 0xccccff },
    { position: 1.0, color: 0xffffff },
  ],
};

// ============================================
// 🏡 BUENA VILLAGE MAP DATA (Sci-Fi Retrofit)
// ============================================
export const BUENA_VILLAGE = {
  name: 'Buena Village',
  description: 'A peaceful village retrofitted with advanced technology',
  spawnPoint: { x: 0, y: 0, z: 0 },
  buildings: [
    {
      id: 'rudeus-house',
      name: "Rudeus's Residence",
      type: 'house',
      position: { x: 10, y: 0, z: -5 },
      size: { width: 8, depth: 6, height: 4 },
      color: 0x333344,
      roofColor: 0x222233,
      emissive: 0x004488,
      emissiveIntensity: 0.1,
    },
    {
      id: 'paul-house',
      name: "Paul's Home",
      type: 'house',
      position: { x: -10, y: 0, z: -5 },
      size: { width: 8, depth: 6, height: 4 },
      color: 0x333344,
      roofColor: 0x222233,
      emissive: 0x004488,
      emissiveIntensity: 0.1,
    },
    {
      id: 'zenith-house',
      name: "Zenith's Clinic",
      type: 'house',
      position: { x: 0, y: 0, z: -15 },
      size: { width: 6, depth: 5, height: 3.5 },
      color: 0x444455,
      roofColor: 0x333344,
      emissive: 0x0088ff,
      emissiveIntensity: 0.15,
    },
    {
      id: 'village-center',
      name: 'Central Plaza',
      type: 'square',
      position: { x: 0, y: 0, z: 10 },
      size: { width: 20, depth: 20, height: 0.5 },
      color: 0x222233,
      emissive: 0x0066aa,
      emissiveIntensity: 0.2,
    },
    {
      id: 'well',
      name: 'Energy Well',
      type: 'well',
      position: { x: 0, y: 0, z: 10 },
      size: { width: 3, depth: 3, height: 2 },
      color: 0x333344,
      roofColor: 0x222233,
      emissive: 0x00ffff,
      emissiveIntensity: 0.3,
    },
  ],
  trees: [
    { position: { x: 15, y: 0, z: 0 }, type: 'cyber-tree', height: 6, radius: 1, color: 0x004422, emissive: 0x008844 },
    { position: { x: -15, y: 0, z: 0 }, type: 'cyber-tree', height: 6, radius: 1, color: 0x004422, emissive: 0x008844 },
    { position: { x: 0, y: 0, z: 20 }, type: 'cyber-tree', height: 6, radius: 1, color: 0x004422, emissive: 0x008844 },
    { position: { x: 20, y: 0, z: 15 }, type: 'crystal-tree', height: 8, radius: 1.2, color: 0x442266, emissive: 0x8844cc },
    { position: { x: -20, y: 0, z: 15 }, type: 'crystal-tree', height: 8, radius: 1.2, color: 0x442266, emissive: 0x8844cc },
    { position: { x: 18, y: 0, z: -10 }, type: 'cyber-tree', height: 6, radius: 1, color: 0x004422, emissive: 0x008844 },
    { position: { x: -18, y: 0, z: -10 }, type: 'cyber-tree', height: 6, radius: 1, color: 0x004422, emissive: 0x008844 },
  ],
  paths: [
    { start: { x: 0, z: 0 }, end: { x: 10, z: -5 }, width: 2, color: 0x1a1a2e, emissive: 0x004466, emissiveIntensity: 0.1 },
    { start: { x: 0, z: 0 }, end: { x: -10, z: -5 }, width: 2, color: 0x1a1a2e, emissive: 0x004466, emissiveIntensity: 0.1 },
    { start: { x: 0, z: 0 }, end: { x: 0, z: -15 }, width: 2, color: 0x1a1a2e, emissive: 0x004466, emissiveIntensity: 0.1 },
    { start: { x: 10, z: -5 }, end: { x: 0, z: 10 }, width: 2, color: 0x1a1a2e, emissive: 0x004466, emissiveIntensity: 0.1 },
    { start: { x: -10, z: -5 }, end: { x: 0, z: 10 }, width: 2, color: 0x1a1a2e, emissive: 0x004466, emissiveIntensity: 0.1 },
  ],
  fences: [
    { start: { x: 25, z: 25 }, end: { x: -25, z: 25 }, height: 1.5, color: 0x333344, emissive: 0x0066aa, emissiveIntensity: 0.1 },
    { start: { x: -25, z: 25 }, end: { x: -25, z: -25 }, height: 1.5, color: 0x333344, emissive: 0x0066aa, emissiveIntensity: 0.1 },
    { start: { x: -25, z: -25 }, end: { x: 25, z: -25 }, height: 1.5, color: 0x333344, emissive: 0x0066aa, emissiveIntensity: 0.1 },
    { start: { x: 25, z: -25 }, end: { x: 25, z: 25 }, height: 1.5, color: 0x333344, emissive: 0x0066aa, emissiveIntensity: 0.1 },
  ],
  gates: [
    { position: { x: 0, z: 25 }, width: 4, height: 3, color: 0x444455, emissive: 0x00aaff, emissiveIntensity: 0.2 },
    { position: { x: 25, z: 0 }, width: 4, height: 3, color: 0x444455, emissive: 0x00aaff, emissiveIntensity: 0.2 },
  ],
  sciFiDecorations: [
    { type: 'hologram', position: { x: 0, y: 5, z: 0 }, color: 0x00ffff, size: 2, text: 'BUENA VILLAGE', area: 'buena-village' },
    { type: 'energy-crystal', position: { x: 5, y: 1, z: 5 }, color: 0x00aaff, size: 1.5, glow: true, area: 'buena-village' },
    { type: 'energy-crystal', position: { x: -5, y: 1, z: 5 }, color: 0xff00aa, size: 1.5, glow: true, area: 'buena-village' },
    { type: 'neon-tube', start: { x: 10, y: 3, z: 0 }, end: { x: 10, y: 3, z: 10 }, color: 0x00ffff, width: 0.15, area: 'buena-village' },
    { type: 'neon-tube', start: { x: -10, y: 3, z: 0 }, end: { x: -10, y: 3, z: 10 }, color: 0x00ffff, width: 0.15, area: 'buena-village' },
    { type: 'floating-platform', position: { x: 8, y: 0.5, z: -8 }, size: { width: 4, depth: 4, height: 0.3 }, color: 0x222233, emissive: 0x0066aa, area: 'buena-village' },
    { type: 'floating-platform', position: { x: -8, y: 0.5, z: -8 }, size: { width: 4, depth: 4, height: 0.3 }, color: 0x222233, emissive: 0x0066aa, area: 'buena-village' },
  ],
};
